/**
 * Single source of truth for shareable app links (S70).
 *
 * Every invite share builds its URL through buildInviteUrl(), so when native
 * universal / deep links are added later only APP_WEB_BASE (and the native link
 * config) changes — call sites stay untouched. The web route app/invite/[code].tsx
 * handles the /invite/<code> path today; the same URL can front a native deep link
 * once associated-domains / intent-filters are configured.
 */
export const APP_WEB_BASE = 'https://caps.ftable.co.il';

/**
 * HOW LONG A REFERRAL CODE IS -- and the reason this constant exists at all.
 *
 * FINAL-QA 2026-08-22: referral_links.referral_code is generated by a COLUMN DEFAULT,
 *   upper(substring(md5(random()::text) from 1 for 8))
 * so every code the database has ever issued is EIGHT characters. All 3,173 of them.
 *
 * Every client entry point required exactly SIX: the /referral field (maxLength 6, a disabled
 * Redeem button and an "Enter a 6-character code." guard), the Home redeem modal (same), and
 * app/invite/[code].tsx, which rejected the very links buildInviteUrl() produces. A real code
 * could not be typed, pasted, or followed. 3,173 codes minted, ZERO redemptions ever -- that
 * number was read as nobody sharing, and it was actually nobody being able to accept.
 *
 * The client is deliberately PERMISSIVE about length now. redeem_referral is the authority and
 * already answers precisely ('Invalid or expired code' / 'Already redeemed' / 'Cannot use own
 * code'), so the client's job is to stop obvious typos, not to re-derive the generator's format
 * and drift away from it a second time.
 */
export const REFERRAL_CODE_MIN = 6;
export const REFERRAL_CODE_MAX = 12;

/** Trim, uppercase, strip anything the generator cannot emit. */
export function normaliseReferralCode(raw: string): string {
  return (raw || '').trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
}

/** Plausible enough to send to the server, which makes the real decision. */
export function isPlausibleReferralCode(raw: string): boolean {
  const c = normaliseReferralCode(raw);
  return c.length >= REFERRAL_CODE_MIN && c.length <= REFERRAL_CODE_MAX;
}

export function buildInviteUrl(code: string): string {
  return `${APP_WEB_BASE}/invite/${code}`;
}
