/**
 * Sound effects for Caps Poker.
 * Uses expo-av Audio when available, silently no-ops when not.
 * Sound files: assets/sounds/*.wav (generated by scripts/generate-sounds.py)
 */

export type SoundName =
  | 'cardPlace'
  | 'cardSelect'
  | 'cardFlip'
  | 'chipsWin'
  | 'lose'
  | 'complete'
  | 'timerLow'
  | 'revealStart'  // placeholder — replace with real tension/drum-roll WAV
  | 'boardWin'     // placeholder — replace with ascending chime WAV
  | 'boardLose';   // placeholder — replace with descending tone WAV

let Audio: any = null;
try {
  Audio = require('expo-av').Audio;
} catch {
  // expo-av not available (e.g. web or build issue) — sounds disabled
}

const soundFiles: Record<SoundName, ReturnType<typeof require> | null> = {
  cardPlace: null,
  cardSelect: null,
  cardFlip: null,
  chipsWin: null,
  lose: null,
  complete: null,
  timerLow: null,
  revealStart: null,
  boardWin: null,
  boardLose: null,
};

// Try to load sound files — they may not exist in all environments
try { soundFiles.cardPlace = require('../assets/sounds/cardPlace.wav'); } catch {}
try { soundFiles.cardSelect = require('../assets/sounds/cardSelect.wav'); } catch {}
try { soundFiles.cardFlip = require('../assets/sounds/cardFlip.wav'); } catch {}
try { soundFiles.chipsWin = require('../assets/sounds/chipsWin.wav'); } catch {}
try { soundFiles.lose = require('../assets/sounds/lose.wav'); } catch {}
try { soundFiles.complete = require('../assets/sounds/complete.wav'); } catch {}
try { soundFiles.timerLow = require('../assets/sounds/timerLow.wav'); } catch {}
try { soundFiles.revealStart = require('../assets/sounds/revealStart.wav'); } catch {}
try { soundFiles.boardWin = require('../assets/sounds/boardWin.wav'); } catch {}
try { soundFiles.boardLose = require('../assets/sounds/boardLose.wav'); } catch {}

const loadedSounds: Partial<Record<SoundName, any>> = {};

export async function preloadSounds(): Promise<void> {
  if (!Audio) return;
  try {
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: false,
      playsInSilentModeIOS: true,  // Play even when iPhone silent switch is on
      staysActiveInBackground: false,
      shouldDuckAndroid: true,
    });
  } catch {
    // Audio mode config not supported in this environment — continue
  }
  for (const [name, file] of Object.entries(soundFiles)) {
    if (!file) continue;
    try {
      const { sound } = await Audio.Sound.createAsync(file);
      loadedSounds[name as SoundName] = sound;
    } catch {
      // Sound file missing or invalid — skip silently
    }
  }
}

export async function playSound(name: SoundName): Promise<void> {
  try {
    // Dynamic import to avoid requiring the store module at import time in tests
    const { useGameStore } = require('../store/gameStore');
    const config = useGameStore.getState().config;
    if (!config.soundEnabled) return;

    const sound = loadedSounds[name];
    if (!sound) return;

    await sound.setPositionAsync(0);
    await sound.playAsync();
  } catch {
    // Silently ignore all audio errors
  }
}
